[build-system]
requires = ['setuptools', 'wheel']
build-backend = 'setuptools.build_meta'

[project]
name = 'nn-dup'
dynamic = ['version', 'dependencies']
description = 'Prefix-aware curation & near-dedup for NN code via MinHash/LSH and AST fingerprints.'
readme = { file = 'README.md', content-type = 'text/markdown' }
license = { file = 'LICENSE' }
requires-python = '>=3.10'
classifiers = [
    'Programming Language :: Python :: 3',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
    'Topic :: Scientific/Engineering :: Artificial Intelligence',
    'Topic :: Software Development :: Code Generators'
]

keywords = ['LLM', 'deduplication', 'MinHash', 'LSH', 'AST', 'neural networks', 'data curation', 'pretraining', 'fine-tuning']

authors = [{ name = 'ABrain One and contributors', email = 'AI@ABrain.one' }]

[project.urls]
Homepage = 'https://ABrain.one'
Repository = 'https://github.com/ABrain-One/nn-dup'
'Bug Tracker' = 'https://github.com/ABrain-One/nn-dup/issues'

[tool.setuptools.dynamic]
version = { file = 'version' }
dependencies = { file = 'requirements.txt' }

[tool.setuptools.packages.find]
where = ['']

[tool.setuptools]
include-package-data = true

[tool.setuptools.data-files]
'*' = ['**/*.json']

[tool.setuptools.package-data]
'*' = ['*.md', 'requirements.txt', 'LICENSE', 'version']

[project.optional-dependencies]
dev = [
    'black>=23.0',
    'isort>=5.0',
    'flake8>=6.0'
]

[project.scripts]
lemur-preprocess = "ab.dup.preprocessing:main"
